name: f_events
description: A library for event handling in Dart.
version: 0.2.0
homepage: https://github.com/shindakioku/events
author: firstlast <shindakioku@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
